FROM ccy1219/docker-distro-ssh:ubuntu-18.04

LABEL maintainer="ccy1219@gmail.com"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
  && apt-get install -y build-essential libgl1-mesa-dev \
  && apt-get install -y software-properties-common git-all htop tree nano curl traceroute \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

