FROM ubuntu:18.04

LABEL maintainer="ccy1219@gmail.com"
ARG ARG_PASSWD


COPY ["/runtime_data/","/runtime_data/"]

RUN echo ${ARG_PASSWD} > /runtime_data/arg_passwd \
    && chmod +x /runtime_data/set_sshd.sh \
    && /runtime_data/set_sshd.sh \
    && rm -rf /runtime_data/

# clean up
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

EXPOSE 22
WORKDIR /root
CMD    ["/usr/sbin/sshd", "-D"]
